### ISSUE TITLE
Widget not not available

### ISSUE THREAD

**Issue by dalb8** [caarmen/FRCAndroidWidget#16]
On stock Nexus 7, Android 5.1 with Google Now Launcher, with 1.6.1 installed from Google Play, there is no French Calendar in the widget list.

**Comment by dalb8** [comment]
However it appears on AOSP launcher.

**Comment by caarmen** [comment]
Thanks for the report.  I currently don't have this device/OS setup to test on, but I'll try to test on some other lollipop devices when I get a chance. 

Silly question though: could you try rebooting the device and see if the widget appears in the Google Now launcher?

**Comment by dalb8** [comment]
Yes the widget appears and is working correctly.

**Comment by dalb8** [comment]
Actually the default launcher is aosp launcher2, which is not related to launcher3
