### ISSUE TITLE
Notification requires internet access

### ISSUE THREAD

**Issue by dalb8** [caarmen/FRCAndroidWidget#37]
I often have my phone (stock lg g4) in airplane mode and I notice that the notification only appears when I connect to the internet.

**Comment by caarmen** [comment]
This is weird.  You can see that the app doesn't require internet at all: https://github.com/caarmen/FRCAndroidWidget/blob/master/app/src/main/AndroidManifest.xml#L34

The only permission is has is to be notified when the device boots, to reschedule the notification.

The app does absolutely nothing related to the internet.

You can try playing around with the notification priority setting to see if LG treats the notification differently depending on its priority.

**Comment by caarmen** [comment]
I just checked with another developer who has the same device and sees the same thing.  This may be an optimization to save battery life, introduced by Marshmallow.

**Comment by caarmen** [comment]
I'm explicitly scheduling the alarm with a flag to **not** wake up the device: https://developer.android.com/reference/android/app/AlarmManager.html#RTC
> This alarm does not wake the device up; if it goes off while the device is asleep, it will not be delivered until the next time the device wakes up.

So apologies about my first remark about the notification priority: that setting will probably have no impact.

I don't think this notification is important enough to wake up the device though...

**Comment by dalb8** [comment]
Thanks for the explanation. I turned off battery optimization for the app and the notification appeared as soon as I turned on the device. It also occurred to me to do the same with the Calendar Storage and now I think I'm getting notifications working there too; I was thinking of going to CyanogenMod about that!
