### ISSUE TITLE
Bug on French calendar app; font feature not functioning 

### ISSUE THREAD

**Issue by onos1** [caarmen/FRCAndroidWidget#49]
#### Expected behavior
Wanted to change to a font, expected to see another type of writings on the app.

#### Actual behavior
The font was reflecting on the words, nothing was changed everything was actually the same.

#### How to reproduce
- download French calendar app
- click the settings at the top right corner 
- click on font
- select any font 
- not reflecting 

* Infinix note 4 
* Operating system: Android 7.0 
* version 1.18.1

#### Recording Of The Bug
https://youtu.be/vOLFXwJBv6E
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@onos/bug-on-french-calendar-app">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by caarmen** [comment]
Thanks for your interest.
This setting is for the widget only. Same as the custom color.

**Comment by caarmen** [comment]
Created an enhancement request to make the setting organization clearer: https://github.com/caarmen/FRCAndroidWidget/issues/50

**Comment by caarmen** [comment]
BTW, what is Utopian.io? Are you filing bug reports in order to earn cryptocurrencies?
